-- MySQL Script generated by MySQL Workbench
-- Fri Oct  7 15:30:33 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema interactions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema interactions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `interactions` DEFAULT CHARACTER SET utf8 ;
USE `interactions` ;

-- -----------------------------------------------------
-- Table `interactions`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interactions`.`Wing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions`.`Wing` (
  `wing_id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NULL,
  PRIMARY KEY (`wing_id`),
  CONSTRAINT `fk_Wing_Staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `interactions`.`Staff` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interactions`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `gender` VARCHAR(16) NULL,
  `wing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Student_Wing1`
    FOREIGN KEY (`wing_id`)
    REFERENCES `interactions`.`Wing` (`wing_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interactions`.`Interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions`.`Interaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NOT NULL,
  `date` DATE NULL,
  `type` VARCHAR(16) NULL,
  `location` VARCHAR(16) NULL,
  `fine` FLOAT NULL,
  `fine_due_date` DATE NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Interaction_Staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `interactions`.`Staff` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interactions`.`Students_Interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions`.`Students_Interactions` (
  `student_id` INT NOT NULL,
  `interaction_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `interaction_id`),
  CONSTRAINT `fk_Student_has_Interaction_Student`
    FOREIGN KEY (`student_id`)
    REFERENCES `interactions`.`Student` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Interaction_Interaction1`
    FOREIGN KEY (`interaction_id`)
    REFERENCES `interactions`.`Interaction` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
